name: Build KMSChanger

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:DebugType=None /p:DebugSymbols=false

    - name: Create Release Package
      run: |
        mkdir release
        copy bin\Release\net6.0-windows\win-x64\publish\kms_changer.exe release\
        copy config.json release\

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: KMSChanger
        path: release\*

    - name: Create GitHub Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
        name: Release ${{ github.sha }}
        tag_name: v${{ github.run_number }}
        body: |
          Автоматический релиз KMSChanger
          Commit: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
